/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newlibrary;

/**
 *
 * @author USER
 */
public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contact_panel2 = new javax.swing.JPanel();
        contact_panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contact_name = new javax.swing.JTextField();
        contact_mail = new javax.swing.JTextField();
        contact_phn = new javax.swing.JTextField();
        contact_msg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contact_address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contact_panel2.setBackground(new java.awt.Color(255, 255, 255));
        contact_panel2.setToolTipText("");
        contact_panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contact_panel1.setBackground(new java.awt.Color(113, 121, 221));
        contact_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(11, 148, 148));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contact Us");
        contact_panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Share your query and ideas with us!");
        contact_panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 30));

        contact_panel2.add(contact_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 85));

        contact_name.setText("Name..");
        contact_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_nameActionPerformed(evt);
            }
        });
        contact_panel2.add(contact_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 232, 30));

        contact_mail.setText("Email..");
        contact_panel2.add(contact_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 232, 27));

        contact_phn.setText("Phone..");
        contact_phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_phnActionPerformed(evt);
            }
        });
        contact_panel2.add(contact_phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 232, 30));

        contact_msg.setText("Message..");
        contact_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_msgActionPerformed(evt);
            }
        });
        contact_panel2.add(contact_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 520, 91));

        contact_address.setColumns(20);
        contact_address.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        contact_address.setRows(5);
        contact_address.setText("Email: bookdestiny1628@gmail.com\nMob : 01783-402650\nCUET, Raozan, Chittagong- 4349, Bangladesh.\n");
        jScrollPane1.setViewportView(contact_address);

        contact_panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 530, 60));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Send");
        contact_panel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contact_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contact_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contact_phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_phnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_phnActionPerformed

    private void contact_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_nameActionPerformed

    private void contact_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_msgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contact_address;
    private javax.swing.JTextField contact_mail;
    private javax.swing.JTextField contact_msg;
    private javax.swing.JTextField contact_name;
    private javax.swing.JPanel contact_panel1;
    private javax.swing.JPanel contact_panel2;
    private javax.swing.JTextField contact_phn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
